Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [4]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [5]:

arr,arr1 = (list(map(int,input().split())) for i in range(2))
arr = np.array(arr)
arr1 = np.array(arr1)
print(np.concatenate((arr,arr1)))
print(np.sort(np.concatenate((arr,arr1))))

1 2 3
56 58 96
[ 1  2  3 56 58 96]
[ 1  2  3 56 58 96]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [8]:
arr = np.array([ [3,2,1] , [7,8,9] , [78,89,25] ])
print(arr.shape,arr.size)

(3, 3) 9


Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [9]:
arr = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape)

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [10]:
arr1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
arr2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])
print(np.vstack((arr1,arr2))) 
print() 
print(np.hstack((arr1,arr2))) 

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]

[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


Questions 6:
How to get unique items and counts of unique items?

In [12]:
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 9])
unique, counts = np.unique(arr_1, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)
print(len(list1))

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  2]
 [16  1]
 [25  1]]
5
